config/routes.rb
Rails.application.routes.draw do
  
  get 'sitemaps/index'
  # resources :posts
    #devise_for :members    
    # devise_for :members do
    #   get '/members/sign_out' => 'devise/sessions#destroy'
    # end
    # devise_scope :members do  
    #    get '/members/sign_out' => 'devise/sessions#destroy'     
    # end
    devise_for :members do
      get '/members/sign_out' => 'devise/sessions#destroy'
    end
    
    get     'sitemap' => 'sitemaps#index', :format => 'xml'
    # get '/sitemap' => 'sitemaps#index'
    
    root 'home#index'
    get '/home', to: 'home#index'
    get '/area', to: 'home#area'
    get '/category', to: 'home#category'
    get '/part', to: 'home#part'
    get '/advertisement', to: 'home#advertisement'
    get '/gallery', to: 'home#gallery-category'
    get '/gallery-category', to: 'home#gallery-category'
    get '/gallery-subject', to: 'home#gallery-subject'
    get '/gallery-part', to: 'home#gallery-part'
    #get '/advertisement', :to => redirect('/tattoo/advertisement.html')
    
    
    
    #partners
    get '/partner1', to: 'partners#partner1'
    get '/partner2', to: 'partners#partner2'
    get '/partner3', to: 'partners#partner3'
    get '/partner4', to: 'partners#partner4'
    get '/partner5', to: 'partners#partner5'
    get '/partner6', to: 'partners#partner6'
    get '/partner7', to: 'partners#partner7'
    
    
    get '/user', to: 'user#index'
    post '/register', to: 'user#register'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    
    #로그인
    #resources :sessions, only: [:new, :create, :destroy]
    # get 'sessions/new'
    #get '/login', to: 'sessions#new'
    #post '/login', to: 'sessions#create'
    #post '/logout', to: 'sessions#destroy'
    
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NEW CAR DEALER</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      
        <!-- Google Fonts -->
        <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i' %>
      
      <meta charset="utf-8">
      <meta content="width=device-width, initial-scale=1.0" name="viewport">
      
      <!-- Favicons -->
      <link href="/tattoo/assets/img/favicon.png" rel="icon">
      <link href="/tattoo/assets/img/apple-touch-icon.png" rel="apple-touch-icon">
      
       <!-- Vendor CSS Files -->
      <link href="/tattoo/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
      <link href="/tattoo/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
      <link href="/tattoo/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
      <link href="/tattoo/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
      <link href="/tattoo/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
      <link href="/tattoo/assets/vendor/venobox/venobox.css" rel="stylesheet">
      <link href="/tattoo/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
      
      
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
      
      <!-- Template Main CSS File -->
      <link href="/tattoo/assets/css/style.css" rel="stylesheet">
      
      
        
  </head>

  <body>
      <!-- ======= Top Bar ======= -->
      <section id="topbar" class="d-none d-lg-block">
        <div class="container d-flex">
          <div class="contact-info mr-auto">
          </div>
          
          <div class="social-links">
            <% if member_signed_in? %>
                <%= current_member.email %>
                <%= link_to "업체정보", edit_member_registration_path %>
                <%= link_to "로그아웃", destroy_member_session_path, method: :delete %>
            <% else %>
                <%= link_to "업체 로그인", member_session_path %>
                <%= link_to "업체 회원가입", "/members/sign_up" %>
            <% end %>
            
          </div>
        </div>
      </section>  
      
      <!-- ======= Header ======= -->
      <header id="header" class="d-flex align-items-center">
        <div class="container d-flex align-items-center">

          <div class="logo mr-auto">
            <!-- <h1 class="text-light"><a href="/home"><span>TATTOO</span> ISANG</a></h1> -->
            <a href="/home"><img src="/tattoo/assets/img/logo.png"></a>
            <!-- <img class="d-block w-100" src="/tattoo/assets/img/banner/banner-image2.png" alt="Second slide" style="width:100%"> -->
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
          </div>
            
          <div style="padding-top: 15px;">
              <div class="form-group has-search d-none d-md-block" style="margin-bottom: 5px; margin-left:50%; margin-right:1%;">
                <span class="icofont-search form-control-feedback"></span>
                <input type="text" class="form-control" placeholder="업체명 검색" style="font-size: 13px;">
              </div>
              
              <nav class="nav-menu d-none d-lg-block">
                <ul>
                  <!-- <li class="active"><a href="#header">Home</a></li> -->
                  <!-- <li class="active"><a class="link" href="/home">Home</a></li> -->
                  <li><a class="link" href="/area">지역별 딜러검색
                      <span><img src="/tattoo/assets/img/new-menu.png"></span></a>
                  </li>
                  <li><a class="link" href="/category">브랜드별 딜러검색
                      <span><img src="/tattoo/assets/img/new-menu.png"></span></a>
                  </li>
                  <li><a class="link" href="/gallery">딜러 견적요청
                      <span><img src="/tattoo/assets/img/new-menu.png"></span></a>
                  </li>
                  <li><a class="link" href="/advertisement">광고안내
                      <span><img src="/tattoo/assets/img/new-menu.png"></span></a>
                  </li>

                  <% if member_signed_in? %>
                      <li class="d-md-none"><%= link_to "회원정보", edit_member_registration_path %></li>
                      <li class="d-md-none"><%= link_to "로그아웃", destroy_member_session_path, method: :delete %></li>
                  <% else %>
                      <li class="d-md-none"><%= link_to "로그인", member_session_path %></li>
                      <li class="d-md-none"><%= link_to "회원가입", "/members/sign_up" %></li>
                  <% end %>
                  <!-- <li class="d-md-none"><a href="/advertisement">test</a></li> -->

                  <!-- <li><a href="#about">About</a></li>
                  <li><a href="#services">Services</a></li>
                  <li><a href="#portfolio">Portfolio</a></li>
                  <li><a href="#team">Team</a></li>
                  <li class="drop-down"><a href="">Drop Down</a>
                    <ul>
                      <li><a href="#">Drop Down 1</a></li>
                      <li class="drop-down"><a href="#">Drop Down 2</a>
                        <ul>
                          <li><a href="#">Deep Drop Down 1</a></li>
                          <li><a href="#">Deep Drop Down 2</a></li>
                          <li><a href="#">Deep Drop Down 3</a></li>
                          <li><a href="#">Deep Drop Down 4</a></li>
                          <li><a href="#">Deep Drop Down 5</a></li>
                        </ul>
                      </li>
                      <li><a href="#">Drop Down 3</a></li>
                      <li><a href="#">Drop Down 4</a></li>
                      <li><a href="#">Drop Down 5</a></li>
                    </ul>
                  </li>
                  <li><a href="#contact">Contact</a></li> -->

                </ul>
              </nav><!-- .nav-menu -->
              
          </div>

          

        </div>
      </header><!-- End Header -->
      
      <%= yield %>
      
      <!-- ======= Footer ======= -->
      <footer id="footer">
        <!-- <div class="footer-top">
          <div class="container">
            <div class="row">

              <div class="col-lg-4">
                <div class="footer-info">
                  <h3>TATTOOIST Korea</h3>
                </div>
              </div>

              <div class="col-lg-4 footer-links">
                <ul>
                  <li><i class="bx bx-chevron-right"></i> <a href="#">대표자 : </a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="#">사업자등록번호 : </a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="#">통신판매업 신고번호 : </a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="#">주소 : </a></li>
                </ul>
              </div>

              <div class="col-lg-4 footer-newsletter">
                <h4>고객센터</h4>
                <p>070 - 1234 - 5678</p>
                <p>상담시간: 평일 10:00 - 18:00</p>
              </div>
            </div>
          </div>
        </div> -->

        <div class="container">
          <div class="copyright">
            &copy; Copyright <strong><span>New Car Dealer</span></strong>. All Rights Reserved
          </div>
        </div>
      </footer>
      <!-- End Footer -->

      <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>
      

      
        <!-- Vendor JS Files -->
      <script src="/tattoo/assets/vendor/jquery/jquery.min.js"></script>
      <script src="/tattoo/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      <script src="/tattoo/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
      <script src="/tattoo/assets/vendor/php-email-form/validate.js"></script>
      <script src="/tattoo/assets/vendor/jquery-sticky/jquery.sticky.js"></script>
      <script src="/tattoo/assets/vendor/waypoints/jquery.waypoints.min.js"></script>
      <script src="/tattoo/assets/vendor/counterup/counterup.min.js"></script>
      <script src="/tattoo/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
      <script src="/tattoo/assets/vendor/venobox/venobox.min.js"></script>
      <script src="/tattoo/assets/vendor/owl.carousel/owl.carousel.min.js"></script>

      <!-- Template Main JS File -->
      <script src="/tattoo/assets/js/main.js"></script>
            
  </body>
</html>